version: '3.7'
services:
  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    platform: linux/amd64  # Added platform specification

  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
      ALLOW_PLAINTEXT_LISTENER: "yes"
    depends_on:
      - zookeeper
    platform: linux/amd64  # Added platform specification

#  ksqldb-server:
#    image: confluentinc/ksqldb-server:latest
#    ports:
#      - "8088:8088"
#    environment:
#      KSQL_LISTENERS: "http://0.0.0.0:8088"
#      KSQL_BOOTSTRAP_SERVERS: "PLAINTEXT://kafka:9092"
#      KSQL_LOGGING_PROCESSING_STREAM_AUTO_CREATE: "true"
#      KSQL_LOGGING_PROCESSING_TOPIC_AUTO_CREATE: "true"
#    depends_on:
#      - kafka
#    platform: linux/amd64  # Addstoped platform specification

#  ksqldb-cli:
#    image: confluentinc/ksqldb-cli:latest
#    environment:
#      KSQL_CONFIG_DIR: "/etc/ksql"
#    entrypoint: /bin/sh
#    tty: true
#    depends_on:
#      - ksqldb-server
#    platform: linux/amd64  # Added platform specification
